### ISSUE TITLE
Get the crate name rsk

### ISSUE THREAD

**Issue by Arkitu** [rust-crates/abandoned#2]
I would like to know if it's possible to retrieve the crate name rsk for a personal library (a port of a python lib)

**Comment by vitiral** [comment]
You can if you want it. May I ask what the personal library is? :smile:

**Comment by Arkitu** [comment]
Yes of course. I participate with my team to the Robocup in the Soccer SSL Light category and we have a python library to interact with the robots named [rsk](https://github.com/robot-soccer-kit/robot-soccer-kit) (robot-soccer-kit). We wanted better performance so we translated it in Rust. We then wanted to make it available for everyone as a Rust library

**Comment by Arkitu** [comment]
We have already uploaded the lib with the name rust-sk, so maybe we could do an exchange
